# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
#zh:
#  languageCode: zh-Hans
#  contentDir: content/zh
#  title: Chinese website title...
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
pt:
  languageCode: zh-Hans
  contentDir: content/pt
  title: Ríad Mattos Nassiffe
  params:
    description: Site para divulgação informações.
  menu:
    main:
      - name: Sobre
        url: '#about'
        weight: 1
      - name: Ensino
        url: '#ensino'
        weight: 1
      - name: Projetos
        url: '#projeto'
        weight: 1
